apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-mqa-property-checker
  labels:
    app: fdk-mqa-property-checker
    fdk.service: fdk-mqa-property-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-mqa-property-checker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-mqa-property-checker
        fdk.service: fdk-mqa-property-checker
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: fdk-mqa-property-checker
          image: fdk-mqa-property-checker
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
          livenessProbe:
            exec:
              command:
                - "true"
          readinessProbe:
            exec:
              command:
                - "true"
      restartPolicy: Always
